// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmcA5Bm9aVIaj7gjuercSpd1CrHPSQHvA',
    appId: '1:479122453630:web:3d3a938edd4a958759d42f',
    messagingSenderId: '479122453630',
    projectId: 'electronics-e-commerce-6fe58',
    authDomain: 'electronics-e-commerce-6fe58.firebaseapp.com',
    storageBucket: 'electronics-e-commerce-6fe58.firebasestorage.app',
    measurementId: 'G-8JSH50YT7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIuTe1J5WlvCHY6E773LH1JoDM-FFQpnU',
    appId: '1:479122453630:android:9fd6181b2ffb38b459d42f',
    messagingSenderId: '479122453630',
    projectId: 'electronics-e-commerce-6fe58',
    storageBucket: 'electronics-e-commerce-6fe58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsoBBMqdbIWeLdEh3TyZWN1sV16lbI0KQ',
    appId: '1:479122453630:ios:2d1b30a76be62fe859d42f',
    messagingSenderId: '479122453630',
    projectId: 'electronics-e-commerce-6fe58',
    storageBucket: 'electronics-e-commerce-6fe58.firebasestorage.app',
    iosClientId: '479122453630-oh01nlpk855pevq85khdq7s6parosh5o.apps.googleusercontent.com',
    iosBundleId: 'com.example.electronicsShop',
  );
}
